apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{api_name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{api_name}}
  template:
    metadata:
      labels:
        app: {{api_name}}
    spec:
      containers:
        - name: api
          image: {{aws_account_id}}.dkr.ecr.{{region}}.amazonaws.com/{{api_name}}:{{api_image_version}}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80          
          env:
            - name: SQS_ARN
              value: {{sqs_arn}}
            - name: AWS_SQS_REGION
              value: {{region}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{api_name}}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: {{api_name}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dev
    nginx.org/client-max-body-size: "13m"
spec:
  ingressClassName: nginx
  rules:
  - host: {{api_name}}.{{domain}}.{{tld}}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{api_name}}
            port:
              number: 80
  tls:
    - hosts:
      - {{api_name}}.{{domain}}.{{tld}}
      secretName: {{api_name}}-{{domain}}-tls
      