apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.api_name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.api_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.api_name }}
    spec:
      containers:
        - name: api
          image: {{ .Values.aws_account_id }}.dkr.ecr.{{ .Values.region }}.amazonaws.com/{{ .Values.api_name }}:{{ .Values.api_image_version }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80          
          env:
            - name: SQS_URL
              value: {{ .Values.sqs_url }}
            - name: AWS_SQS_REGION
              value: {{ .Values.region }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api_name }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.api_name }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dev
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.api_name }}.{{ .Values.domain }}.{{ .Values.tld }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.api_name }}
            port:
              number: 80
  tls:
    - hosts:
      - {{ .Values.api_name }}.{{ .Values.domain }}.{{ .Values.tld }}
      secretName: {{ .Values.api_name }}-{{ .Values.domain }}-tls
      